use_frameworks!

platform :ios, '9.0'

target 'FFmpegTutorial-iOS' do
  pod 'FFmpegTutorial', :path => '../../'
  pod 'Masonry'
end

pre_install do |installer|
  puts `../../download-vendor.sh github ios`
end
