use_frameworks!

platform :osx, '10.11'

target 'FFmpegTutorial-macOS' do
  pod 'FFmpegTutorial',:path => '../../'
  pod 'Masonry'
end

pre_install do |installer|
  puts `../../download-vendor.sh github macos`
end

